apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-metrics-app
  labels:
    app: go-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-metrics-app
  template:
    metadata:
      labels:
        app: go-metrics-app
    spec:
      containers:
        - name: go-metrics-app
          image: go-metrics-app:latest  # Uses the local Minikube image
          imagePullPolicy: Never  # <- Tells Kubernetes to use local image
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-metrics-app-service
spec:
  selector:
    app: go-metrics-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # Change to NodePort if needed
